### ISSUE TITLE
small improvements in README.md

### ISSUE THREAD

**Issue by FedorRomanov** [tomtom-international/configuration-service#1]
Hello Rijn,

Section **Using Git and .gitignore** in README.md can be very helpful for an inexperienced git user. I would like to suggest following small improvements:

1.  [github docs](https://help.github.com/articles/ignoring-files/) recommend to name global _.gitignore_ file *.gitignore_global*
2.  Worth mentioning that running _git config_ command just sets up the global file, but it does not create it. Mac/Unix users have to run _touch .gitignore_global_ to create the file
3.  [This gist](https://gist.github.com/NV/221353)  has an example of typical global _.gitignore_ file in easy copy-paste format

Also there is a typo in section **A Simple Example** _"The good new is that the design ...."_

**Comment by rijnb** [comment]
Pushed commit 99abaea to fix it. Please check if it’s clearer now.
Thanks for the comment.

https://github.com/tomtom-international/configuration-service/commit/99abaea7741d2a7b987c1b8a4c10ac8e626680b2
