### ISSUE TITLE
improve monitoring: add health check 

### ISSUE THREAD

**Issue by FedorRomanov** [tomtom-international/configuration-service#3]
Health check can be used by load-balancer to put in/out node in/from the cluster. It must return _200 OK_ only if configuration-service is started and runs well(json-configuration is loaded and parsed successfully). In other cases an error must be returned.

Also it is good idea to return some meta-info in the body, e.g.
1. configuration-service version
2. build-date
3. startup-date
4. branch built
5. value of ApplicationConfigurationData.startupConfigurationURI
6. e.t.c.

**Comment by rijnb** [comment]
The health check is already provided RootResource.java by GET /status. It will indeed return 200 if all is OK.
Next to that, there is a GET /version call which returns the POM version and the configuration URI.

So, which stuff is missing (apart from build date and start date, which I find less relevant)?

**Comment by FedorRomanov** [comment]
Indeed, `RootResource.java` provides all required services: 
1. health check
2. displaying of current version and address of loaded configuration. Displaying other params are less important.

I would recommend to rename `RootResource.java` somehow to hint a developer it worth looking into and mention these services in main README.md

I am closing this issue.
