### ISSUE TITLE
redundant dependency: apache-httpclient

### ISSUE THREAD

**Issue by FedorRomanov** [tomtom-international/configuration-service#5]
dependency
`        <dependency>
            <groupId>commons-httpclient</groupId>
            <artifactId>commons-httpclient</artifactId>
        </dependency>
`
is declared in `pom.xml` , but not actually used. configuration-service builds well without it.

Either remove the dependency or use it actually the project. If the latter will be chosen(see Issue #6), then httpclient version must be updated - *3.1* is used now, but *4.5* is already available

**Comment by rijnb** [comment]
Done. Removed.
