### ISSUE TITLE
add hjson support and convert examples to hjson

### ISSUE THREAD

**Issue by FedorRomanov** [tomtom-international/configuration-service#7]
It is assumed that _configuration-service_ actual configuration will be modified by humans: configuration.json file must be updated by configuration owner and re-deployed. However, json-format was designed mainly for software communication, hence json is not user-friendly.
To improve json readability,  [project hjson](http://hjson.org) was developed. Hjson includes following features facilitating json manipulations:

1. commas are optional and can be omitted
2. it is allowed and encouraged to use comments
3. object names can be specified without quotes. This makes them easier to read.
4. one can specify strings without quotes.

There is lib supporting integration hjson for java.

**Comment by rijnb** [comment]
There is value in having the configuration file be a standardized format. JSON and XML are standard formats and widely supported by editing and management tools.
HJSON is not a standard format and it's not widely supported. I do not recommend using customer or proprietary data formats for generic services.
If the human operator finds it hard to create or edit JSON (or XML) files (which I can understand), there is an ample choice of tools to support him or her with producing JSON (or XML) files, such as database tools, IDEs etc. HJSON attacks the issue of operator-friendliness from the wrong angle by introducing a non-standard format. I'd rather support operators by pointing them at good (open-source?) JSON/XML editing or management tools.

**Comment by rijnb** [comment]
One more thought: If an operator would prefer to use HJSON, you could consider keeping the master configuration file as HJSON and use an automatic conversion tool of HJSON-to-JSON during deployment. Only the resulting JSON file would be deployed in that case. The HJSON file itself would never be deployed, as it wasn't meant for the machine, just for the human.
In fact, this schema would work for any format you prefer over JSON or XML. Even database formats, with automatic export to JSON at deployment time.
